# Generated by Django 3.1.13 on 2022-02-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='pickup_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='pickup_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_centre', to='givers.pickupcentre'),
        ),
        migrations.AlterField(
            model_name='pickupcentre',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centre', to='givers.state'),
        ),
    ]
