# Generated by Django 3.1.13 on 2022-02-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0002_auto_20220217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pickup_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre', to='givers.pickupcentre'),
        ),
        migrations.AlterField(
            model_name='pickupcentre',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='givers.state'),
        ),
    ]
