# Generated by Django 3.1.13 on 2022-02-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0004_auto_20220217_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ondeliverytransaction',
            name='settlement',
        ),
    ]
