# Generated by Django 3.1.13 on 2022-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0005_remove_ondeliverytransaction_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
