# Generated by Django 3.1.13 on 2022-02-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0006_auto_20220218_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pickup_location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
