# Generated by Django 3.1.13 on 2022-02-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0007_auto_20220218_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='give',
            name='gift_status',
            field=models.CharField(blank=True, choices=[('unpicked', 'unpicked'), ('requested', 'requested'), ('received', 'received'), ('redeemed', 'redeemed'), ('on-delivery', 'on-delivery'), ('on-pickup', 'on-pickup'), ('paid', 'paid')], default='unpicked', max_length=30),
        ),
    ]
