# Generated by Django 3.1.13 on 2022-03-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0009_profile_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='giver_contacted',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='receiver_contacted',
        ),
    ]
