# Generated by Django 3.1.13 on 2022-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0010_auto_20220316_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
