# Generated by Django 3.1.13 on 2022-04-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0011_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
