# Generated by Django 3.1.13 on 2022-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0012_subscription_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
