# Generated by Django 3.1.13 on 2022-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0014_auto_20220406_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='pickup_location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
