# Generated by Django 3.1.13 on 2022-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0016_auto_20220410_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='ticket',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
