# Generated by Django 3.1.13 on 2022-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0018_auto_20220504_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=8000000000),
        ),
    ]
