# Generated by Django 3.1.13 on 2022-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0019_auto_20220504_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
