# Generated by Django 3.1.13 on 2022-05-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0020_destinationcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcharge',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='givers.state'),
        ),
    ]
