# Generated by Django 3.1.13 on 2022-05-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0022_auto_20220511_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondeliverytransaction',
            name='items_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
