# Generated by Django 3.1.13 on 2022-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0023_ondeliverytransaction_items_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
