# Generated by Django 3.1.13 on 2022-05-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0024_transaction_items_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondeliverytransaction',
            name='items_id',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='items_id',
            field=models.JSONField(default=list, null=True),
        ),
    ]
