# Generated by Django 3.1.13 on 2022-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0025_auto_20220522_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpickup',
            name='items_id',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
