# Generated by Django 3.1.13 on 2022-05-23 08:19

from django.db import migrations, models
import givers.models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0028_auto_20220522_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='receiver_number',
            field=models.IntegerField(blank=True, null=True, validators=[givers.models.validate_number]),
        ),
    ]
