# Generated by Django 3.1.13 on 2022-05-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0030_auto_20220527_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='give',
            name='category',
            field=models.CharField(blank=True, choices=[('fur', 'Furniture'), ('clo', 'Clothes'), ('sho', 'Shoes'), ('toy', 'toys'), ('ele', 'Electronics'), ('bag', 'Bags'), ('fon', 'mobile-phones'), ('lap', 'Laptops'), ('buk', 'Books'), ('kit', 'Kitchen-utensils'), ('bic', 'Bicyle'), ('ace', 'Accessories'), ('fud', 'Food-stuffs'), ('gro', 'Groceries'), ('gen', 'Generator'), ('bty', 'Beauty-product'), ('nat', 'Natives')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('fur', 'Furniture'), ('clo', 'Clothes'), ('sho', 'Shoes'), ('toy', 'toys'), ('ele', 'Electronics'), ('bag', 'Bags'), ('fon', 'mobile-phones'), ('lap', 'Laptops'), ('buk', 'Books'), ('kit', 'Kitchen-utensils'), ('bic', 'Bicyle'), ('ace', 'Accessories'), ('fud', 'Food-stuffs'), ('gro', 'Groceries'), ('gen', 'Generator'), ('bty', 'Beauty-product'), ('nat', 'Natives')], max_length=100),
        ),
    ]
