# Generated by Django 3.1.13 on 2022-05-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0032_auto_20220527_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10, null=True),
        ),
    ]
