# Generated by Django 3.1.13 on 2022-05-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0033_auto_20220527_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10),
        ),
    ]
