# Generated by Django 3.1.13 on 2022-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0034_auto_20220527_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(default='Head Office'),
        ),
    ]
