# Generated by Django 3.1.13 on 2022-06-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0035_auto_20220527_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
